### ISSUE TITLE
Feature Request: Support for cascading variable interpolation in YAML configurations

### ISSUE THREAD

**Issue by OAuthBringer** [OAuthBringer/mcp-gen#1]
## Problem Description

The current templating engine processes variables with single-pass interpolation, which prevents cascading variable references where one variable references another variable that itself contains template syntax.

## Current Behavior

Variables are loaded as-is into the Jinja2 context without pre-processing, meaning template expressions within variable definitions are not resolved before being used in other template expressions.

### Example Configuration (Currently Fails)

```yaml
variables:
  user_root: "/Users/oauthbringer/"
  dev_root: "{{ variables.user_root }}/dev"
  project_root: "{{ variables.dev_root }}/slarglebart"

servers:
  filesystem:
    command: "npx"
    args:
      - "{{ variables.project_root }}"  # This fails
```

### Error Result
The `dev_root` variable contains the literal string `"{{ variables.user_root }}/dev"` rather than the resolved path, causing downstream failures when `project_root` tries to reference it.

## Expected Behavior

Variables should support cascading interpolation, allowing hierarchical path construction and more maintainable configurations:

```yaml
variables:
  user_root: "/Users/oauthbringer/"
  dev_root: "{{ variables.user_root }}/dev"           # Should resolve to "/Users/oauthbringer/dev"
  project_root: "{{ variables.dev_root }}/slarglebart" # Should resolve to "/Users/oauthbringer/dev/slarglebart"
```

## Technical Analysis

**Root Cause**: In `template_engine.py`, variables are added directly to the context without recursive processing:

```python
# Current implementation
variables = config.get('variables', {})
context = {
    'variables': variables,  # Raw dict, not processed
    'secrets': secrets.get('secrets', {}),
    'env': dict(__import__('os').environ)
}
```

**Solution Approach**: Variables should be processed in dependency order, resolving template expressions recursively until all variables are fully resolved.

## Proposed Implementation

1. **Dependency Analysis**: Parse variable definitions to build a dependency graph
2. **Topological Sort**: Process variables in dependency order to avoid circular references
3. **Recursive Resolution**: Process each variable through the template engine until fully resolved
4. **Circular Reference Detection**: Detect and report circular variable dependencies

## Benefits

- **Maintainable Configurations**: Reduce duplication and improve configuration hierarchy
- **Path Portability**: Enable environment-agnostic configurations with cascading paths  
- **User Experience**: Match user expectations from other templating systems (Helm, etc.)

## Workaround

Currently, users must manually flatten all variable references:

```yaml
variables:
  user_root: "/Users/oauthbringer/"
  dev_root: "/Users/oauthbringer/dev"                    # Manually flattened
  project_root: "/Users/oauthbringer/dev/slarglebart"    # Manually flattened
```

## Priority

**Medium** - This enhances usability but existing functionality remains unaffected. Current single-level interpolation continues to work as expected.
